username = input('Введите имя пользователя: ')
title = input('Введите заголовок: ')
content = input('Укажите заметку: ')
status = input('Укажите статус заметки: ')
created_date = int(input('Укажите дату заметки в формате дд.мм.гг: '))
issue_date = int(input('Укажите крайнюю дату заметки в формате дд.мм.гг: '))
